### ISSUE TITLE
configure the server

### ISSUE THREAD

**Issue by hbarbosa02** [BonneVoyager/MetaTrader4-Bridge#3]
Hi, I'm trying to use your script to export orders from my mt4, however I'm having trouble with configuring the server.

First let me describe my situation, the application is hosted on a virtual machine in a server, I left the default host and port configuration and I am trying to access by a nodejs application using the external ip of the server and the port set as the default in the script, however I can not connect, the module always retries the error **METATRADER4 can not connect with tcp://ip:port**.

**Comment by BonneVoyager** [comment]
Hi @hbarbosa02,

there can be numerous problems which could occur along the way.

First, how do you try to access your virtual machine server, do you use following library?
https://github.com/BonneVoyager/node-mt4-zmq-bridge

**Comment by hbarbosa02** [comment]
yes I am...

**Comment by BonneVoyager** [comment]
OK, then please check the logs from the Terminal of MetaTrade 'Experts' tab. It should say something like `MetaTrader4Bridge USDCHF,1H: initialized` in one of the lines.

Then, let's check whether you can access the MT4 Expert with telnet `telnet ip port` (e.g. `telnet 192.168.1.108 5555`).

It the log doesn't say that MetaTrader4Bridge is initialized, please copy the log here, so I can check why it's not starting.
