### ISSUE TITLE
MetaTrader4Bridge.mq4 fails to compile

### ISSUE THREAD

**Issue by leonfiedler** [BonneVoyager/MetaTrader4-Bridge#4]
Hey there!

On MetaEditor MetaTrader4Bridge.mq4 fails to compile with the error code:
`'&' - parameter passed as reference, variable expected	MetaTrader4Bridge.mq4	Line190, Column 27`

zeromq is up and running properly.

**Comment by BonneVoyager** [comment]
Hey @leonfiedler,

I checked with updated code `1.2.0` and it works properly now. Does it work for you too?

**Comment by leonfiedler** [comment]
@BonneVoyager 
Awesome, works now! Thanks a lot :)
